

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TechnicalShop.Databases
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class HardwareShoEntities : DbContext
{
    public HardwareShoEntities()
        : base("name=HardwareShoEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Feedback> Feedback { get; set; }

    public virtual DbSet<Product> Product { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

}

}

